export const FETCH_TODOS_STARTED = 'FETCH_TODOS_STARTED'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const ADD_TODOS_STARTED = 'ADD_TODOS_STARTED'
export const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS'
export const ADD_TODOS_FAILURE = 'ADD_TODOS_FAILURE'

export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'